/* Includes *******************/

#include <Windows.h>
#include <Winternl.h>
#include <TChar.h>
#include <BCrypt.h>

#include <Field.h>

/* Defines ********************/

#define MOLD_WIDTH             4
#define MOLD_HEIGHT            4
#define BLOCK_START_POSITION_X 4
#define BLOCK_START_POSITION_Y 0

typedef struct _CURRENT_BLOCK {
    BLOCK_SHAPE   Shape;
    BLOCK_HEADING Heading;
    INT           X, Y;
} CURRENT_BLOCK, *PCURRENT_BLOCK;

/* Global variables ***********/

static const CUBE_TYPE     Block[BLOCK_SHAPE_COUNT][BLOCK_HEADING_COUNT][MOLD_HEIGHT][MOLD_WIDTH] = {
    // T
    {
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_RED, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_RED, CUBE_TYPE_RED, CUBE_TYPE_RED, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_RED, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_RED, CUBE_TYPE_RED, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_RED, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_RED, CUBE_TYPE_RED, CUBE_TYPE_RED, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_RED, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_RED, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_RED, CUBE_TYPE_RED, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_RED, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        }
    },
    // I
    {
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_BLUE, CUBE_TYPE_BLUE, CUBE_TYPE_BLUE, CUBE_TYPE_BLUE},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_BLUE, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_BLUE, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_BLUE, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_BLUE, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_BLUE, CUBE_TYPE_BLUE, CUBE_TYPE_BLUE, CUBE_TYPE_BLUE},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_BLUE, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_BLUE, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_BLUE, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_BLUE, CUBE_TYPE_VOID}
        }
    },
    // S
    {
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_VOID}
        }
    },
    // rS
    {
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_PINK, CUBE_TYPE_PINK, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_PINK, CUBE_TYPE_PINK},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_PINK, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_PINK, CUBE_TYPE_PINK, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_PINK, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_PINK, CUBE_TYPE_PINK, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_PINK, CUBE_TYPE_PINK},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_PINK, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_PINK, CUBE_TYPE_PINK, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_PINK, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        }
    },
    // L
    {
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_YELLOW, CUBE_TYPE_YELLOW, CUBE_TYPE_YELLOW},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_YELLOW}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_YELLOW, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_YELLOW, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_YELLOW, CUBE_TYPE_YELLOW, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_YELLOW, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_YELLOW, CUBE_TYPE_YELLOW, CUBE_TYPE_YELLOW, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_YELLOW, CUBE_TYPE_YELLOW, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_YELLOW, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_YELLOW, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        }
    },
    // rL
    {
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_GREEN},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_GREEN, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        }
    },
    // Rect
    {
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        },
        {
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_GREEN, CUBE_TYPE_GREEN, CUBE_TYPE_VOID},
            {CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID, CUBE_TYPE_VOID}
        }
    }
};
static       CUBE_TYPE     MainField[FIELD_HEIGHT][FIELD_WIDTH];
static       CUBE_TYPE     BufferField[FIELD_HEIGHT][FIELD_WIDTH];
static       CURRENT_BLOCK CurrentBlock;

/* Private functions **********/

static BOOL FdpInitializeField(VOID)
{
    for (UINT i = 0; i < FIELD_HEIGHT; i++)
    {
        for (UINT j = 0; j < FIELD_WIDTH; j++)
        {
            MainField[i][j] = BufferField[i][j] = CUBE_TYPE_VOID;
        }
    }
    return TRUE;
}

static BOOL FdpSetCurrentBlock(BOOL bRandom, BLOCK_SHAPE Shape)
{
    /* 1. 블록 위치 정보 초기화 */

    CurrentBlock.X       = BLOCK_START_POSITION_X;
    CurrentBlock.Y       = BLOCK_START_POSITION_Y;
    CurrentBlock.Heading = BLOCK_HEADING_UP;

    /* 2. 블록 모양 생성 */

    if (bRandom)
    {

        NTSTATUS status = BCryptGenRandom(
            NULL,
            &CurrentBlock.Shape,
            sizeof(CurrentBlock.Shape),
            BCRYPT_USE_SYSTEM_PREFERRED_RNG
        );

        if (NT_ERROR(status))
        {
            return FALSE;
        }

        CurrentBlock.Shape %= BLOCK_SHAPE_COUNT;
    }
    else
    {
        CurrentBlock.Shape = Shape;
    }

    return TRUE;
}

/* Public functions ***********/

BOOL FdInitialize(VOID)
{
    FdpInitializeField();
    FdpSetCurrentBlock(TRUE, 0);
    return TRUE;
}

BOOL FdUninitialize(VOID)
{
    return TRUE;
}

BOOL FdMoveBlockDown(VOID)
{

}

BOOL FdMoveBlockLeft(VOID)
{

}

BOOL FdMoveBlockRight(VOID)
{

}

BOOL FdSetCurrentBlock(BOOL bRandom, BLOCK_SHAPE Shape)
{
    return FdpSetCurrentBlock(bRandom, Shape);
}

CUBE_TYPE FdGetScreenCube(INT x, INT y)
{

}
