#ifndef GAME_RESOURCE_NAME_H
#define GAME_RESOURCE_NAME_H

#define IDB_CUBE_VOID   100
#define IDB_CUBE_RED    101
#define IDB_CUBE_YELLOW 103
#define IDB_CUBE_GREEN  104
#define IDB_CUBE_BLUE   105
#define IDB_CUBE_PINK   106
#define IDB_CUBE_WALL   107

#endif
