#ifndef GAME_RESOURCE_H
#define GAME_RESOURCE_H

#define IDB_CUBE_VOID    100
#define IDB_CUBE_RED     101
#define IDB_CUBE_YELLOW  103
#define IDB_CUBE_GREEN   104
#define IDB_CUBE_BLUE    105
#define IDB_CUBE_PINK    106
#define IDB_CUBE_WALL    107
#define IDB_CUBE_PREVIEW 108

#ifndef RC_INVOKED

#include <Windows.h>
#include <TChar.h>

typedef UINT RESOURCE_BITMAP;
enum {
    RESOURCE_BITMAP_VOID,
    RESOURCE_BITMAP_RED,
    RESOURCE_BITMAP_YELLOW,
    RESOURCE_BITMAP_GREEN,
    RESOURCE_BITMAP_BLUE,
    RESOURCE_BITMAP_PINK,
    RESOURCE_BITMAP_PREVIEW,
    RESOURCE_BITMAP_WALL,
    RESOURCE_BITMAP_COUNT
};

BOOL    RsInitialize(HINSTANCE hInstance);
BOOL    RsUninitialize(VOID);
HBITMAP RsGetBitmapHandle(RESOURCE_BITMAP Index);

#endif

#endif
